name: Security audit

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 0' # weekly on Sunday 03:00 UTC

jobs:
  audit:
    name: pnpm audit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Enable corepack for pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run pnpm audit
        run: pnpm audit --level=moderate --audit-level=moderate
